---
- hosts: localhost
  vars:
    brew_tap:
      - homebrew/cask-fonts
      - hudochenkov/sshpass
      - tavianator/tap
      - buo/cask-upgrade
      - railwaycat/emacsmacport

    brew_packages:
      - atool
      - bash
      - bat
      - bfs
      - chezmoi
      - cmake
      - code-minimap
      - colordiff
      - coreutils
      - cowsay
      - dark-mode
      - dockutil
      - duti
      - exiftool
      - fd
      - ffmpeg
      - figlet
      - fzf
      - ghq
      - gifsicle
      - gitui
      - gnu-sed
      - graphviz
      - helm
      - htop
      - icdiff
      - isync
      - jump
      - mas
      - mpv
      - msmtp
      - mu
      - ncdu
      - neovim
      - nmap
      - npm
      - pandoc
      - peco
      - pngpaste
      - putty
      - qpdf
      - qrencode
      - rar
      - reattach-to-user-namespace
      - ripgrep
      - ruby
      - rust
      - schappim/ocr/ocr
      - spaceship
      - sshpass
      - stow
      - svn
      - syncthing
      - telnet
      - terraform
      - the_silver_searcher
      - tmux
      - trash
      - tree-sitter
      - ugit
      - universal-ctags
      - vim
      - wget
      - wordnet
      - yarn
      - youtube-dl

    brew_packages_remove:
      - exa

    brew_casks:
      - anydesk
      - evkey
      - firefox
      - font-cascadia-code
      - font-cascadia-code-pl
      - font-cascadia-mono
      - font-cascadia-mono-pl
      - font-iosevka-curly-slab
      - font-jetbrains-mono-nerd-font
      - font-juliamono
      - font-lato
      - font-source-code-pro
      - google-chrome
      - istat-menus
      - iterm2
      - karabiner-elements
      - keepassxc
      - keycastr
      - kitty
      - lens
      - maciasl
      - microsoft-edge
      - microsoft-office
      - microsoft-teams
      - mos
      - postman
      - rectangle
      - shottr
      - teamviewer
      - textmate
      - visual-studio-code

    brew_casks_remove:
      - alt-tab
      - browserosaurus
      - dropbox
      - google-drive
      - hiddenbar
      - maccy

    appstore_app:
      - 1440147259 # AdGuard for Safari
      - 937984704 # Amphetamine
      - 1355679052 # Dropover
      - 975890633 # HotKey App
      - 1295203466 # Microsoft Remote Desktop
      - 747648890 # Telegram

    appstore_app_remove:
      - 1547052291 # Translatium

  tasks:
    - name: Appstore install apps
      shell: |
        mas install {{ item }}
      with_items: "{{ appstore_app }}"
      tags:
        - appstore

    - name: Brew tap
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap {{ item }}
      with_items: "{{ brew_tap }}"
      tags:
        - brew
        - brew-tap

    - name: Brew install packages
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install {{ item }}
      with_items: "{{ brew_packages }}"
      tags:
        - brew
        - brew-packages

    - name: Brew install casks
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask {{ item }}
      with_items: "{{ brew_casks }}"
      tags:
        - brew
        - brew-casks
