---
- hosts: localhost
  vars:
    brew_tap: 
      - homebrew/cask-fonts
      - hudochenkov/sshpass
      - tavianator/tap
      - buo/cask-upgrade
      - railwaycat/emacsmacport

    brew_packages:
      - bash
      - bat
      - bfs
      - cmake
      - chezmoi
      - code-minimap
      - colordiff
      - coreutils
      - cowsay
      - dockutil
      - exa
      - fd
      - figlet
      - fzf
      - ghq
      - gitui
      - gnu-sed
      - graphviz
      - htop
      - icdiff
      - jump
      - mas
      - ncdu
      - neovim
      - nmap
      - npm
      - peco
      - putty
      - rar
      - reattach-to-user-namespace
      - ripgrep
      - ruby
      - rust
      - sshpass
      - stow
      - svn
      - telnet
      - the_silver_searcher
      - tmux
      - tree-sitter
      - ugit
      - universal-ctags
      - vim
      - wget
      - wordnet
      - yarn

    brew_casks: 
      - alt-tab
      - anydesk
      - browserosaurus
      - dropbox
      - evkey
      - firefox
      - font-jetbrains-mono-nerd-font
      - font-source-code-pro
      - font-cascadia-mono
      - font-cascadia-mono-pl
      - font-cascadia-code
      - font-cascadia-code-pl
      - google-chrome
      - google-drive
      - hiddenbar
      - istat-menus
      - iterm2
      - karabiner-elements
      - keepassxc
      - keycastr
      - kitty
      - maccy
      - maciasl
      - microsoft-edge
      - microsoft-office
      - microsoft-teams
      - mos
      - postman
      - rectangle
      - shottr
      - teamviewer
      - textmate
      - visual-studio-code

    appstore_app:
      - 1440147259 # AdGuard for Safari
      - 937984704  # Amphetamine
      - 1355679052 # Dropover
      - 975890633  # HotKey App
      - 1295203466 # Microsoft Remote Desktop
      - 747648890  # Telegram
      - 1547052291 # Translatium

  tasks:
    - name: Appstore install apps
      shell: |
        mas install {{ item }}
      with_items: "{{ appstore_app }}"
      tags:
      - appstore

    - name: Brew tap
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew tap {{ item }}
      with_items: "{{ brew_tap }}"
      tags:
      - brew
      - brew-tap

    - name: Brew install packages
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install {{ item }}
      with_items: "{{ brew_packages }}"
      tags:
      - brew
      - brew-packages

    - name: Brew install casks
      shell: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask {{ item }}
      with_items: "{{ brew_casks }}"
      tags:
      - brew
      - brew-casks
