---
- hosts: localhost
  vars:
    dockitems_to_remove:
      - Launchpad
      - Mail
      - Contacts
      - Notes
      - Reminders
      - Maps
      - Photos
      - Messages
      - TV
      - Music
      - Podcasts
      - FaceTime
      - iTunes
      - iBooks
      - App Store
      - System Preferences
      - Calendar

    dockitems_to_persist:
      - name: Microsoft Edge
        path: "/Applications/Microsoft Edge.app"
        pos: 2
      - name: Microsoft Teams
        path: "/Applications/Microsoft Teams.app" 
        pos: 3
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 4
      - name: Telegram
        path: "/Applications/Telegram.app"
        pos: 5
      - name: KeePassXC
        path: "/Applications/KeePassXC.app"
        pos: 6
      - name: iTerm
        path: "/Applications/iTerm.app"
        pos: 7
      - name: Notes
        path: "/System/Applications/Notes.app"
        pos: 8
      - name: AnyDesk
        path: "/Applications/AnyDesk.app"
        pos: 9

  tasks:
    - name: Remove all crap from Dock
      shell: dockutil --remove '{{ item }}'
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"
      tags:
      - dock
      - dock-remove

    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: "{{ dockitems_to_persist }}"
      tags:
      - dock
      - dock-check
     
    - name: Fix order
      shell: dockutil --move '{{ item.name }}' --position '{{ item.pos }}'
      with_items: "{{ dockitems_to_persist }}"
      tags:
      - dock
      - dock-order
